### ISSUE TITLE
pyparsing.exceptions.ParseException for filename*=...

### ISSUE THREAD

**Issue by cmrschwarz** [JohnDoee/pyrfc6266#1]
First, thank you for the great Library!
The following Content-Dispositon (which is from a real HTTP Response by a Seafile instance):

```
atachment;filename*="utf-8' '100MB.zip"
```

causes `pyrfc6266.parse_filename` to throw a`pyparsing.exceptions.ParseException` with the message
`Expected end of text, found ';'  (at char 10), (line:1, col:11)`

Removing the `*` from `filename*=...` makes it work, so that seems to be where the problem lies.
Firefox and Chromium both correctly deduce the filename.
Would it be possible to fix this?

Here the complete reproduction for convenience:
```python
import pyrfc6266
pyrfc6266.parse_filename("atachment;filename*=\"utf-8' '100MB.zip\"")
```

**Comment by JohnDoee** [comment]
Working around edge-cases not matching is what implementing RFCs is all about (for some reason :) )

Is attachment intentionally misspelled ?

**Comment by cmrschwarz** [comment]
Thank you for  taking time to look at this. 
I'm very sorry about the misspelling, I must have messed up during reformatting.

It raises an interesting point though, as the [RFC](https://datatracker.ietf.org/doc/html/rfc6266) states (in 4.2)
```
Unknown or unhandled disposition types SHOULD be handled by
recipients the same way as "attachment"
``` 
Browsers indeed accept an arbitrary string in that position.  
Example: https://httpbin.org/response-headers?Content-Disposition=foobar;filename=filename_correctly_deduced.json
Downloads correctly for me. 

the library code even seems to have originally intended to allow that  too with this `disp_ext_type`: 
```python
disposition_type = (
    CaselessLiteral("inline") | CaselessLiteral("attachment") | disp_ext_type
)
```
I feel bad about just raising issues though, so if you're busy I can submit a PR for this sometime next week when I find the time. That one is also not really urgent for me, because every sane host uses 'attachement' anyways.
But for a library that's literally named after the rfc ... :).

**Comment by JohnDoee** [comment]
It's no bother really and you're right about following the RFC.

Everything should be going through now.

```python
>>> import requests
>>> r = requests.get('https://httpbin.org/response-headers?Content-Disposition=foobar;filename=filename_correctly_deduced.json')
>>> import pyrfc6266
>>> pyrfc6266.requests_response_to_filename(r)
'filename_correctly_deduced.json'
```

**Comment by cmrschwarz** [comment]
Thank you so much.
Closing this as resolved.
